Transform: 'AWS::Serverless-2016-10-31'
Description: Trigger Lambda function from API

Resources:
  MySAMLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_function
      Runtime: python3.10
      CodeUri: ./
      MemorySize: 128
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
# Transform: 'AWS::Serverless-2016-10-31'
# Description: Trigger Lambda functions from API

# Resources:
#   MySAMLambda:
#     Type: 'AWS::Serverless::Function'
#     Properties:
#       Handler: lambda_function.lambda_handler
#       Runtime: python3.10
#       CodeUri: ./
#       MemorySize: 128
#       Events:
#         ApiEvent:
#           Type: Api
#           Properties:
#             Path: /
#             Method: get

#   MySecondLambda:
#     Type: 'AWS::Serverless::Function'
#     Properties:
#       Handler: second_lambda_function.lambda_handler
#       Runtime: python3.10
#       CodeUri: ./
#       MemorySize: 128
#       Events:
#         ApiEvent:
#           Type: Api
#           Properties:
#             Path: /second
#             Method: post
